---
- name: ACTIVAR GESTORES QM
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    GESTOR_UNO: QM1
    GESTOR_DOS: QM2
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: false
  tasks:

    # - name: INICIAR GESTOR DE COLA QM1
    #   ibmi_cl_command:
    #     cmd: STRMQM MQMNAME("{{ GESTOR_UNO }}")
    #   ignore_errors: true

    # - name: INICIAR GESTOR DE COLA QM1
    #   ibmi_cl_command:
    #     cmd: STRMQM MQMNAME("{{ GESTOR_DOS }}")
    #   ignore_errors: true

    - name: CONSULTA GESTOR MQ1
      ibmi_cl_command:
        cmd: DSPMQMSTS MQMNAME(MQ1) Output(*)
      register: mq1_status
      ignore_errors: true

    - name: ESTADO GESTOR MQ1
      debug:
        msg: "{{ mq1_status.stdout | regex_search('.*RUNNING.*', multiline=True, ignorecase=True) }}"
      ignore_errors: true

    - name: CONSULTA GESTOR MQ2
      ibmi_cl_command:
        cmd: DSPMQMSTS MQMNAME(QM2) Output(*)
      register: mq2_status
      ignore_errors: true

    - name: ESTADO GESTOR MQ2
      debug:
        msg: "{{ mq2_status.stdout | regex_search('.*RUNNING.*', multiline=True, ignorecase=True) }}"
      ignore_errors: true