---
- name: Gathering Job Responses
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    JOB_NAME: PRUEBA
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:

    - name: LISTAR SUBSISTEMAS
      ibmi_cl_command:
        cmd: system "WRKACTJOB SBS(QHTTPSVR) JOB(PRUEBA)"
      register: somevar

    - name: debug
      debug:
        var: somevar

    