---
- name: Gathering Job Responses
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    JOB_NAME: PRUEBA
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:
  
    - name: FINALIZAR SUBSISTEMA
      ibmi_end_subsystem:
        subsystem: M400SBS
        how_to_end: '*IMMED'
      tags:
      - bajar_subsistema

    - name: INICIAR SUBSISTEMA
      ibm.power_ibmi.ibmi_cl_command:
        cmd: "QSYS/STRSBS SBSD(M400LIB/M400SBS)"

    - name: ESTADO SUBSISTEMA INICIADO
      ibmi_display_subsystem:
        subsystem: M400SBS
      register: subsystem_state

    - name: MOSTRAR ESTADO
      debug:
        var: subsystem_state