---
- name: Gathering Job Responses
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    JOB_NAME: PRUEBA
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:

    - name: LISTAR SUBSISTEMAS
      ibmi_display_subsystem:
        subsystem: M400SBS
      register: somevar

    - name: debug
      debug:
        msg: "{{ somevar.active_jobs | map(attribute='JOB_NAME') | flatten | map(attribute='JOB_STATUS') | flatten }}"

    

