---
- name: Gathering Job Responses
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    JOB_NAME: PRUEBA
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:
    
    - name: prueba
      ibm.power_ibmi.ibmi_cl_command:
        cmd: "QSYS/STRSBS SBSD(M400LIB/M400SBS)"