---
- name: Gathering Job Responses
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    JOB_NAME: PRUEBA
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:

    - name: LISTAR SUBSISTEMAS
      ibmi_sql_query:
        sql: "JOB_NAME,JOB_TYPE,JOB_STATUS,SUBSYSTEMFROM TABLE(QSYS2.ACTIVE_JOB_INFO()) B WHERE SUBSYSTEM='M400SBS'"
      register: somevar

    - name: debug
      debug:
        var: somevar

    

