---
- name: FINALIZAR SUBSISTEMA MQ
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    SUBSYS_NAME: QMQM
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:
  
    - name: FINALIZAR SUBSISTEMA MQ 
      ibmi_end_subsystem:
        subsystem: "{{ SUBSYS_NAME }}"
        how_to_end: '*IMMED'