---
- name: Gathering Job Responses
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    JOB_NAME: NAME
    SUBSYS_NAME: NAME
    SUBSYS_LIB: NAME
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:
  
    - name: FINALIZAR SUBSISTEMA MQ 
      ibmi_end_subsystem:
        subsystem: "{{ SUBSYS_NAME }}"
        how_to_end: '*IMMED'
      register: subsystem_down
      tags:
      - bajar_subsistema

    - name: MOSTRAR ESTADO SUBSISTEMA FINALIZADO
      debug:
        var: subsystem_down

    - name: INICIAR SUBSISTEMA MQ
      ibm.power_ibmi.ibmi_cl_command:
        cmd: "QSYS/STRSBS SBSD({{ SUBSYS_LIB }}/{{ SUBSYS_NAME }})"
      register: subsystem_up

    - name: VALIDAR SUBSISTEMA MQ ARRIBA
      ibmi_cl_command:
        cmd: "WRKACTJOB SBS(M400SBS) JOB({{ JOB_NAME }}*)"
      register: wrk_job
    
    - name: output
      debug:
        var: wrk_job.stdout