---
- name: HOLDEAR TRABAJOS IBM
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    JOB_NAME: CMC499
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:

    - name: INFORMACIÓN ESTADO INICIAL TAREA
      ibmi_sql_query:
        sql: "SELECT JOB_NAME_SHORT,JOB_STATUS FROM TABLE(QSYS2.ACTIVE_JOB_INFO()) B WHERE JOB_NAME_SHORT = '{{ JOB_NAME }}'"
      register: select_job_result

    - name: ESTADO TAREA 
      debug:
        var: select_job_result
