---
- name: HOLDEAR TRABAJOS IBM
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    JOB_NAME: PRUEBA
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:

    - name: INFO JOB
      ibmi_job:
        name: "{{ JOB_NAME }}"
        type: "*BATCH"
        joblog: true
      register: select_job_result

    - name: ESTADO TAREA 
      debug:
        var: select_job_result.job_info

