---
- name: LIBERAR TRABAJO IBM
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    JOB_NAME: PRUEBA
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:

    - name: INFORMACIÓN ESTADO INICIAL TAREA
      ibmi_sql_query:
        sql: "SELECT JOB_NAME_SHORT,JOB_STATUS FROM TABLE(QSYS2.ACTIVE_JOB_INFO()) B WHERE JOB_NAME_SHORT = '{{ JOB_NAME }}'"
      register: select_job_result

    - name: LIBERAR TRABAJO
      ibmi_cl_command:
        cmd: "RLSJOB JOB({{ JOB_NAME }})"
      when: select_job_result.row | selectattr('JOB_STATUS', '==', 'HLD') | map(attribute='JOB_STATUS') | list
      failed_when:
        - select_job_result.row | selectattr('JOB_STATUS', '==', 'HLD') | map(attribute='JOB_STATUS') | list
      tags:
      - liberar_trabajo

    - name: COMPROBAR ESTADO LIBERADO
      ibmi_sql_query:
        sql: "SELECT JOB_NAME_SHORT,JOB_STATUS FROM TABLE(QSYS2.ACTIVE_JOB_INFO()) B WHERE JOB_NAME_SHORT = '{{ JOB_NAME }}'"
      register: liberar_job_status

    - name: ESTADO TAREA 
      debug:
        var: liberar_job_status.row