---
- name: SUBIR CANALES MQ
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    SBSD: QMQM
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: false
  tasks:

    - name: VALIDAR CANAL QM1
      ibmi_cl_command:
        cmd: PNGMQMCHL CHLNAME(QM1.TO.QM2) MQMNAME(QM1)
        joblog: true
      ignore_errors: true
      register: validate_qm1_chanel

    - name: ESTADO CANAL QM1 (INACTIVO)
      debug:
        msg: |
          "EL LISTENER NO SE ENCUENTRA ACTIVO: CODIGO (AMQ8020)"
      when: validate_qm1_chanel.job_log | regex_search('AMQ8020', ignorecase=True)


    - name: ESTADO CANAL QM1 (ACTIVO)
      debug:
        msg: |
          "EL LISTENER SE ENCUENTRA ACTIVO: CODIGO (AMQ9514)"
      when: validate_qm1_chanel.job_log | regex_search('AMQ9514', ignorecase=True)

    # - name: INICIAR CANAL QM1.TO.QM2
    #   ibmi_cl_command:
    #     cmd: QMQM/STRMQMCHL CHLNAME(QM1.TO.QM2) MQMNAME(QM1)
    #   ignore_errors: true
    #   register: estado_canal1

    # - name: debug
    #   debug:
    #     var: estado_canal1

    # - name: INICIAR CANAL QM2.TO.QM1
    #   ibmi_cl_command:
    #     cmd: QMQM/STRMQMCHL CHLNAME(QM2.TO.QM1) MQMNAME(QM2)
    #   ignore_errors: true
    #   register: estado_canal2

    # - name: INFORMACIÓN ESTADO DEL CANAL
    #   debug:
    #     var: estado_canal2