---
- name: BAJAR AGENTE MQ
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    JOB_NAME: QEJBSVR
    SBSD: QMQM
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: false
  tasks:

    - name: INICIAR MQMQ
      ibmi_cl_command:
        cmd: STRSBS SBSD(QMQM/QMQM)
      tags:
      - iniciar_mqmq

    - name: OBTENIENDO INFORMACIÓN DEL SUBSISTEMA QMQM
      ibmi_sql_query:
        sql: "SELECT SBSD,STATUS FROM QSYS2.SUBSYSTEM_INFO WHERE SBSD = '{{ SBSD }}'"
      register: subsys_status

    - name: VALIDANDO SUBSISTEMA QMQM
      debug:
        msg: "El ESTADO DEL SUBSISTEMA ESTÁ ACTIVO"
      when: subsys_status.row | selectattr('STATUS', '==', 'ACTIVE') | map(attribute='STATUS') | list
      failed_when:
        - subsys_status.row | selectattr('STATUS', '!=', 'ACTIVE') | map(attribute='STATUS') | list

    - name: INICIAR GESTOR DE COLA QM1
      ibmi_cl_command:
        cmd: STRMQM MQMNAME("{{ GESTOR_UNO }}")

    - name: INICIAR GESTOR DE COLA QM1
      ibmi_cl_command:
        cmd: STRMQM MQMNAME("{{ GESTOR_DOS }}")
      
    - name: CONSULTA GESTOR MQ1
      ibmi_cl_command:
        cmd: DSPMQMSTS MQMNAME(QM1) Output(*)
      register: mq1_status
      ignore_errors: true

    - name: ESTADO GESTOR MQ1
      debug:
        msg: "{{ mq1_status.stdout | regex_search('.*RUNNING.*', multiline=True, ignorecase=True) }}"
      ignore_errors: true

    - name: CONSULTA GESTOR MQ2
      ibmi_cl_command:
        cmd: DSPMQMSTS MQMNAME(QM2) Output(*)
      register: mq2_status
      ignore_errors: true

    - name: ESTADO GESTOR MQ2
      debug:
        msg: "{{ mq2_status.stdout | regex_search('.*RUNNING.*', multiline=True, ignorecase=True) }}"
      ignore_errors: true