---
- name: BAJAR AGENTE MQ
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    SBSD: QMQM
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: false
  tasks:

    - name: INICIAR GESTOR DE COLA QM1
      ibmi_cl_command:
        cmd: QMQM/STRMQMCHL CHLNAME(QM1.TO.QM2) MQMNAME(QM1)
