---
- name: Gathering Job Responses
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:

    - name: INICIAR SUBSISTEMA MQ
      ibm.power_ibmi.ibmi_cl_command:
        cmd: "STRSBS SBSD(M400LIB/M400SBS)"
      register: subsystem_up

    - name: INFORMACIÓN ESTADO SUBSISTEMA
      ibmi_sql_query:
        sql: "SELECT SBSD,STATUS FROM QSYS2.SUBSYSTEM_INFO WHERE SBSD = 'M400SBS'"
      register: info_sub
      tags:
      - status_sub

    # POR VALIDAR CUANTO ESTÉ EL AGENTE
    - name: START MQ
      ibmi_cl_command:
        cmd: "STRMQM MQMNAME()"
      when: info_sub.row | selectattr('STATUS', 'equalto', 'ACTIVE') | map(attribute='STATUS') | list

    - name: DISPLAY MQ STATUS
      ibmi_cl_command:
        cmd: "DSPMQMSTS MQMNAME() Output(*)"
      register: display_mq

    - name: OUTPUT MQ STATUS
      debug:
        var: display_mq