---
- name: Gathering Job Responses
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    JOB_NAME: PRUEBA
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:
  
    - name: WORK ACTIVE JOB
      ibmi_cl_command:
        cmd: "WRKACTJOB SBS(M400SBS) JOB(PRUEBA*)"
      register: wrk_job
      



