---
- name: Gathering Facts from AS400
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
  #connection: ssh
  gather_facts: true
  tasks:

      - name: Invoke sql commands
        community.general.mssql_script:
          login_user: ''
          login_password: ''
          login_host: '150.238.77.146'
          login_port: '1433'
          db: Operaciones
          script: 'SELECT 1'
        register: resultado

