---
- name: Gathering Facts from AS400
  hosts: all
  connection: ssh
  gather_facts: true
  tasks:

    - name: Return ibmi_facts
      ibm.power_ibmi.ibmi_facts:
      register: as400_facts

    - name: debug ibmi_facts
      debug:
        var: as400_facts