---
- name: Gathering Facts from AS400
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
  connection: ssh
  gather_facts: true
  tasks:

    - name: debug ibmi_facts
      msg: |
        "{{ gather_facts['hostname'] }}"