---
- name: Gathering Facts from AS400
  hosts: all
  connection: ssh
  gather_facts: true
  tasks:

    - name: Return ibmi_facts
      ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
      ibmi_cl_command:
        cmd: 'WRKUSRJOB OFICIAL5'
      register: as400_facts

    - name: debug ibmi_facts
      debug:
        var: as400_facts