---
- name: Gathering Facts from AS400
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:

    - name: Testing
      ibmi_job:
        user: "QSECOFRs"
        type: "*BATCH"