---
- name: Gathering Facts from AS400
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:

    - name: get job 
      ibmi_job:
        user: "QSECOFRs"
        type: "*BATCH"
      register: job_info_ibm
    
    - name: Debug job info
      debug:
        msg: |
          "Info: {{ job_info_ibm }}"