---
- name: TESTING TEMPLATE
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    SBSD: QMQM
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: false
  tasks:

    - name: VALIDAR 
      ibmi_sql_query:
        sql: "SELECT LOCAL_PORT, JOB_NAME, JOB_TYPE, FROM qsys2.netstat_job_info WHERE LOCAL_PORT = '1411' and JOB_NAME = 'RUNMQ'"
      register: select_job_result

    - name: Debug canal
      debug:
        var: select_job_result