---
- name: TESTING TEMPLATE
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    SBSD: QMQM
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: false
  tasks:

    - name: VALIDAR CANAL
      ibmi_cl_command:
        cmd: PNGMQMCHL CHLNAME(QM1.TO.QM2) MQMNAME(QM1)
      register: validar_canal

    - name: Debug canal
      debug:
        var: validar_canal