---
- name: Gathering Job Responses
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:

    # - name: FINALIZAR MQMQ
    #   ibmi_cl_command:
    #     cmd: ENDMQM MQMNAME(*ALL) OPTION(*IMMED) ENDCCTJOB(*YES) RCDMQMIMG(*NO) TIMEOUT(1)
    
    - name: CONSULTA GESTOR MQ1
      ibmi_cl_command:
        cmd: DSPMQMSTS MQMNAME("{{ item }}") Output(*)
      loop:
        - MQ1
        - MQ2
      register: mq1_status

    - name: ESTADO GESTOR MQ1
      debug:
        msg: "{{ mq1_status.stdout | regex_search('.*RUNNING.*', multiline=True, ignorecase=True) }}"

    # - name: CONSULTA GESTOR MQ2
    #   ibmi_cl_command:
    #     cmd: DSPMQMSTS MQMNAME(QM2) Output(*)
    #   register: mq1_status

    # - name: ESTADO GESTOR MQ2
    #   debug:
    #     msg: "{{ mq1_status.stdout | regex_search('.*RUNNING.*', multiline=True, ignorecase=True) }}"