---
- name: Gathering Job Responses
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:

    # - name: FINALIZAR MQMQ
    #   ibmi_cl_command:
    #     cmd: ENDMQM MQMNAME(*ALL) OPTION(*IMMED) ENDCCTJOB(*YES) RCDMQMIMG(*NO) TIMEOUT(1)
    
    - name: ESTATUS GESTOR MQ1
      ibmi_cl_command:
        cmd: DSPMQMSTS MQMNAME(QM1) Output(*)
      register: mq1_status

    - name: status mq1
      debug:
        var: mq1_status.stdout_lines | map(attribute='Queue Manager Status') | list