---
- name: Get jobs in queu
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:
  
    - name: get jobs in queue
      ibmi_sql_query:
        sql: ""
        # become_user: ''
        # become_user_password: ''
      register: sql_query_output

    - name: debug jobs in queue
      debug:
        msg: |
          "Details: {{ sql_query_output }}"
