---
- name: Gathering Job Responses
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    JOB_NAME: PRUEBA
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:

    - name: INFORMACIÓN ESTADO INICIAL TAREA
      ibmi_sql_query:
        sql: "SELECT JOB_NAME_SHORT,JOB_STATUS FROM TABLE(QSYS2.ACTIVE_JOB_INFO()) B WHERE JOB_NAME_SHORT = '{{ JOB_NAME }}'"
      register: select_job_result

    - name: RHOLDEAR TRABAJO
      ibmi_cl_command:
        cmd: 'HLDJOB JOB(prueba)'
      when: "{{ select_job_result.row | selectattr('JOB_STATUS', '!=', 'HLD') | map(attribute='JOB_STATUS') | list | length == 0 }}" 

    # - name: RESULTADO HOLDEAR TRABAJO
    #   debug:
    #     var: prueba_output

    - name: COMPROBAR ESTADO HOLDEADO
      ibmi_sql_query:
        sql: "SELECT JOB_NAME_SHORT,JOB_STATUS FROM TABLE(QSYS2.ACTIVE_JOB_INFO()) B WHERE JOB_NAME_SHORT = '{{ JOB_NAME }}'"
      register: holded_job_status

    - name: ESTADO TAREA 
      debug:
        var: "{{ holded_job_status.row | selectattr('JOB_STATUS', 'equalto', 'HLD') | map(attribute='JOB_STATUS') | list | length == 0 }}"
      

