---
- name: Gathering Job Responses
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: true
  tasks:

    - name: list all the ethernet port information
      ibmi_sql_query:
        sql: "SELECT JOB_NAME,JOB_NAME_SHORT,JOB_TYPE,JOB_STATUS,SUBSYSTEM FROM TABLE(QSYS2.ACTIVE_JOB_INFO()) B WHERE JOB_NAME_SHORT = 'QDBSRV01' AND JOB_STATUS = 'EVTW'"
        joblog: false 
      register: ip_listing

    - name: debug variable
      debug:
        msg: |
          "exito"
      when: "'EVTW' in {{ ip_listing.row }}" 

